### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by grandles1212** [EricDavidEpperson/SWGE_BB_Rpi_controller#1]
I've been playing around with your code, I was curious. You mention there is a way to control the head. Do you happen to have the command you send to do that?

**Comment by EricDavidEpperson** [comment]
Hi! 

If you're not a part of the Galaxy's Edge Discord server, I'd recommend joining. The following google sheets is available in the #makerspace pinned comments. It has a lot of information on various SWGE technical devices. The link should take you to the "Astromech Droid Controller" tab with lots of information including motor commands. Look under the heading "Motor Control" for examples and other information regarding controlling R (and I'd assume C) series droid heads.

https://docs.google.com/spreadsheets/d/13P_GE6tNYpGvoVUTEQvA3SQzMqpZ-SoiWaTNoJoTV9Q/edit#gid=941538687

**Comment by grandles1212** [comment]
Thank you that worked exactly!
-------- Original message --------From: Eric Epperson ***@***.***> Date: 8/31/22  1:12 PM  (GMT-06:00) To: EricDavidEpperson/SWGE_BB_Rpi_controller ***@***.***> Cc: grandles1212 ***@***.***>, Author ***@***.***> Subject: Re: [EricDavidEpperson/SWGE_BB_Rpi_controller] Question (Issue #1) 
Hi!
If you're not a part of the Galaxy's Edge Discord server, I'd recommend joining. The following google sheets is available in the #makerspace pinned comments. It has a lot of information on various SWGE technical devices. The link should take you to the "Astromech Droid Controller" tab with lots of information including motor commands. Look under the heading "Motor Control" for examples and other information regarding controlling R (and I'd assume C) series droid heads.
https://docs.google.com/spreadsheets/d/13P_GE6tNYpGvoVUTEQvA3SQzMqpZ-SoiWaTNoJoTV9Q/edit#gid=941538687
